---
default:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: storage/development.sqlite3
test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: storage/test.sqlite3
production:
  adapter: sqlite3
  pool: 5
  timeout: 5000
